name: Build Godot project

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Godot CLI
        run: |
          curl -L -o godot.zip https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
    unzip godot.zip
    mv Godot_v4.2.1-stable_linux.x86_64 godot
    chmod +x godot

      - name: Run tests
        run: ./godot --headless -s tests/test_suite.gd
